/* Swipely — template (theme) definitions.
 * Each template fully describes how a slide is painted. `pro: true` themes are
 * the upsell: free users can preview them but the watermark stays locked on and
 * export is gated (wired up when Stripe lands).
 *
 * Colors are plain CSS color strings. `bg` is either:
 *   { type: 'solid', color }
 *   { type: 'gradient', from, to, angle }   // angle in degrees, 0 = left->right
 */
window.TEMPLATES = [
  {
    id: 'midnight',
    name: 'Midnight',
    pro: false,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#0f172a' },
    titleColor: '#ffffff',
    bodyColor: '#cbd5e1',
    accentColor: '#38bdf8',
    pageColor: '#64748b',
    brandColor: '#ffffff',
    watermarkColor: '#475569',
  },
  {
    id: 'paper',
    name: 'Paper',
    pro: false,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#faf7f2' },
    titleColor: '#1a1a1a',
    bodyColor: '#4b4b4b',
    accentColor: '#e1463b',
    pageColor: '#b8b0a4',
    brandColor: '#1a1a1a',
    watermarkColor: '#c8c0b4',
  },
  {
    id: 'mono',
    name: 'Mono',
    pro: false,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'solid', color: '#000000' },
    titleColor: '#ffffff',
    bodyColor: '#a3a3a3',
    accentColor: '#ffffff',
    pageColor: '#525252',
    brandColor: '#ffffff',
    watermarkColor: '#404040',
  },
  {
    id: 'mint',
    name: 'Mint',
    pro: false,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#ecfdf5' },
    titleColor: '#064e3b',
    bodyColor: '#047857',
    accentColor: '#10b981',
    pageColor: '#6ee7b7',
    brandColor: '#064e3b',
    watermarkColor: '#a7f3d0',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#f97316', to: '#db2777', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#ffe4e6',
    accentColor: '#fde68a',
    pageColor: '#fbcfe8',
    brandColor: '#ffffff',
    watermarkColor: '#fbcfe8',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#0ea5e9', to: '#1e3a8a', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#dbeafe',
    accentColor: '#67e8f9',
    pageColor: '#93c5fd',
    brandColor: '#ffffff',
    watermarkColor: '#93c5fd',
  },
  {
    id: 'grape',
    name: 'Grape',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#7c3aed', to: '#4c1d95', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#e9d5ff', accentColor: '#c4b5fd',
    pageColor: '#a78bfa', brandColor: '#ffffff', watermarkColor: '#6d28d9',
  },
  {
    id: 'forest',
    name: 'Forest',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#10b981', to: '#064e3b', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#d1fae5', accentColor: '#6ee7b7',
    pageColor: '#34d399', brandColor: '#ffffff', watermarkColor: '#065f46',
  },
  {
    id: 'ember',
    name: 'Ember',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ef4444', to: '#7f1d1d', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#fecaca', accentColor: '#fca5a5',
    pageColor: '#f87171', brandColor: '#ffffff', watermarkColor: '#991b1b',
  },
  {
    id: 'royal',
    name: 'Royal',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#4f46e5', to: '#1e1b4b', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#e0e7ff', accentColor: '#a5b4fc',
    pageColor: '#818cf8', brandColor: '#ffffff', watermarkColor: '#3730a3',
  },
  {
    id: 'berry',
    name: 'Berry',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ec4899', to: '#7c3aed', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#fbcfe8', accentColor: '#f9a8d4',
    pageColor: '#f472b6', brandColor: '#ffffff', watermarkColor: '#9d174d',
  },
  {
    id: 'sunrise',
    name: 'Sunrise',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#fbbf24', to: '#f97316', angle: 135 },
    titleColor: '#7c2d12', bodyColor: '#9a3412', accentColor: '#ffffff',
    pageColor: '#c2410c', brandColor: '#7c2d12', watermarkColor: '#fdba74',
  },
  {
    id: 'carbon',
    name: 'Carbon',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#0a0a0a' },
    titleColor: '#ffffff', bodyColor: '#a3a3a3', accentColor: '#a3e635',
    pageColor: '#525252', brandColor: '#ffffff', watermarkColor: '#404040',
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#1f2937' },
    titleColor: '#ffffff', bodyColor: '#cbd5e1', accentColor: '#f472b6',
    pageColor: '#64748b', brandColor: '#ffffff', watermarkColor: '#475569',
  },
  {
    id: 'sand',
    name: 'Sand',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'solid', color: '#f5e6c8' },
    titleColor: '#422006', bodyColor: '#713f12', accentColor: '#b45309',
    pageColor: '#ca8a04', brandColor: '#422006', watermarkColor: '#d6c39a',
  },
  {
    id: 'ice',
    name: 'Ice',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#e0f2fe' },
    titleColor: '#0c4a6e', bodyColor: '#075985', accentColor: '#0284c7',
    pageColor: '#38bdf8', brandColor: '#0c4a6e', watermarkColor: '#bae6fd',
  },
];

window.getTemplate = function (id) {
  return window.TEMPLATES.find((t) => t.id === id) || window.TEMPLATES[0];
};
