/* Swipely — template (theme) definitions.
 * Each template fully describes how a slide is painted. `pro: true` themes are
 * the upsell: free users can preview them but the watermark stays locked on and
 * export is gated (wired up when Stripe lands).
 *
 * Colors are plain CSS color strings. `bg` is either:
 *   { type: 'solid', color }
 *   { type: 'gradient', from, to, angle }   // angle in degrees, 0 = left->right
 */
window.TEMPLATES = [
  {
    id: 'midnight',
    name: 'Midnight',
    pro: false,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#0f172a' },
    titleColor: '#ffffff',
    bodyColor: '#cbd5e1',
    accentColor: '#38bdf8',
    pageColor: '#64748b',
    brandColor: '#ffffff',
    watermarkColor: '#475569',
  },
  {
    id: 'paper',
    name: 'Paper',
    pro: false,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#faf7f2' },
    titleColor: '#1a1a1a',
    bodyColor: '#4b4b4b',
    accentColor: '#e1463b',
    pageColor: '#b8b0a4',
    brandColor: '#1a1a1a',
    watermarkColor: '#c8c0b4',
  },
  {
    id: 'mono',
    name: 'Mono',
    pro: false,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'solid', color: '#000000' },
    titleColor: '#ffffff',
    bodyColor: '#a3a3a3',
    accentColor: '#ffffff',
    pageColor: '#525252',
    brandColor: '#ffffff',
    watermarkColor: '#404040',
  },
  {
    id: 'mint',
    name: 'Mint',
    pro: false,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#ecfdf5' },
    titleColor: '#064e3b',
    bodyColor: '#047857',
    accentColor: '#10b981',
    pageColor: '#6ee7b7',
    brandColor: '#064e3b',
    watermarkColor: '#a7f3d0',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#f97316', to: '#db2777', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#ffe4e6',
    accentColor: '#fde68a',
    pageColor: '#fbcfe8',
    brandColor: '#ffffff',
    watermarkColor: '#fbcfe8',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#0ea5e9', to: '#1e3a8a', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#dbeafe',
    accentColor: '#67e8f9',
    pageColor: '#93c5fd',
    brandColor: '#ffffff',
    watermarkColor: '#93c5fd',
  },
  {
    id: 'grape',
    name: 'Grape',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#7c3aed', to: '#4c1d95', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#e9d5ff', accentColor: '#c4b5fd',
    pageColor: '#a78bfa', brandColor: '#ffffff', watermarkColor: '#6d28d9',
  },
  {
    id: 'forest',
    name: 'Forest',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#10b981', to: '#064e3b', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#d1fae5', accentColor: '#6ee7b7',
    pageColor: '#34d399', brandColor: '#ffffff', watermarkColor: '#065f46',
  },
  {
    id: 'ember',
    name: 'Ember',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ef4444', to: '#7f1d1d', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#fecaca', accentColor: '#fca5a5',
    pageColor: '#f87171', brandColor: '#ffffff', watermarkColor: '#991b1b',
  },
  {
    id: 'royal',
    name: 'Royal',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#4f46e5', to: '#1e1b4b', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#e0e7ff', accentColor: '#a5b4fc',
    pageColor: '#818cf8', brandColor: '#ffffff', watermarkColor: '#3730a3',
  },
  {
    id: 'berry',
    name: 'Berry',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ec4899', to: '#7c3aed', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#fbcfe8', accentColor: '#f9a8d4',
    pageColor: '#f472b6', brandColor: '#ffffff', watermarkColor: '#9d174d',
  },
  {
    id: 'sunrise',
    name: 'Sunrise',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#fbbf24', to: '#f97316', angle: 135 },
    titleColor: '#7c2d12', bodyColor: '#9a3412', accentColor: '#ffffff',
    pageColor: '#c2410c', brandColor: '#7c2d12', watermarkColor: '#fdba74',
  },
  {
    id: 'carbon',
    name: 'Carbon',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#0a0a0a' },
    titleColor: '#ffffff', bodyColor: '#a3a3a3', accentColor: '#a3e635',
    pageColor: '#525252', brandColor: '#ffffff', watermarkColor: '#404040',
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#1f2937' },
    titleColor: '#ffffff', bodyColor: '#cbd5e1', accentColor: '#f472b6',
    pageColor: '#64748b', brandColor: '#ffffff', watermarkColor: '#475569',
  },
  {
    id: 'sand',
    name: 'Sand',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'solid', color: '#f5e6c8' },
    titleColor: '#422006', bodyColor: '#713f12', accentColor: '#b45309',
    pageColor: '#ca8a04', brandColor: '#422006', watermarkColor: '#d6c39a',
  },
  {
    id: 'ice',
    name: 'Ice',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#e0f2fe' },
    titleColor: '#0c4a6e', bodyColor: '#075985', accentColor: '#0284c7',
    pageColor: '#38bdf8', brandColor: '#0c4a6e', watermarkColor: '#bae6fd',
  },
  // ── Gothic & Dark Themes ──────────────────────────────────────────
  {
    id: 'mystic',
    name: 'Mystic',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#1a0033', to: '#2d0a5c', angle: 135 },
    titleColor: '#e9d5ff',
    bodyColor: '#c4b5fd',
    accentColor: '#d8b4fe',
    pageColor: '#9d4edd',
    brandColor: '#e9d5ff',
    watermarkColor: '#5a189a',
  },
  {
    id: 'gothic',
    name: 'Gothic',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#0f0015', to: '#2d0a4e', angle: 135 },
    titleColor: '#ffd60a',
    bodyColor: '#fff066',
    accentColor: '#ffd60a',
    pageColor: '#7209b7',
    brandColor: '#ffd60a',
    watermarkColor: '#3a0ca3',
  },
  {
    id: 'vampire',
    name: 'Vampire',
    pro: true,
    font: "'Georgia', serif",
    bg: { type: 'gradient', from: '#1a0a1a', to: '#4d0f2e', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#ff6b9d',
    accentColor: '#c70039',
    pageColor: '#8b0000',
    brandColor: '#ffffff',
    watermarkColor: '#5a0a2e',
  },
  // ── Cute & Playful Themes ──────────────────────────────────────────
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    pro: true,
    font: "'Comic Sans MS', cursive, sans-serif",
    bg: { type: 'gradient', from: '#ff69b4', to: '#ff1493', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#fff0f6',
    accentColor: '#ffe4f0',
    pageColor: '#ffb6d9',
    brandColor: '#ffffff',
    watermarkColor: '#ff6bb6',
  },
  {
    id: 'pastel-dreams',
    name: 'Pastel Dreams',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ffc0db', to: '#c0dbff', angle: 45 },
    titleColor: '#6b4c9a',
    bodyColor: '#8b7ab8',
    accentColor: '#e8a4d2',
    pageColor: '#b8a8d9',
    brandColor: '#6b4c9a',
    watermarkColor: '#e0d4f7',
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ffb3d9', to: '#b3d9ff', angle: 90 },
    titleColor: '#d946a6',
    bodyColor: '#ec4899',
    accentColor: '#f472b6',
    pageColor: '#fda4af',
    brandColor: '#d946a6',
    watermarkColor: '#fce7f3',
  },
  {
    id: 'peach',
    name: 'Peach',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ffb3a7', to: '#ffe4b5', angle: 135 },
    titleColor: '#c2410c',
    bodyColor: '#ea580c',
    accentColor: '#ff6347',
    pageColor: '#fb923c',
    brandColor: '#c2410c',
    watermarkColor: '#ffedd5',
  },
  // ── Nature & Organic Themes ──────────────────────────────────────────
  {
    id: 'forest-deep',
    name: 'Forest Deep',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#0d4e2e', to: '#051d10', angle: 135 },
    titleColor: '#d1fae5',
    bodyColor: '#a7f3d0',
    accentColor: '#6ee7b7',
    pageColor: '#34d399',
    brandColor: '#d1fae5',
    watermarkColor: '#065f46',
  },
  {
    id: 'autumn',
    name: 'Autumn',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#a16207', to: '#5a3a1a', angle: 135 },
    titleColor: '#fffbeb',
    bodyColor: '#fef3c7',
    accentColor: '#fcd34d',
    pageColor: '#d97706',
    brandColor: '#fffbeb',
    watermarkColor: '#78350f',
  },
  {
    id: 'sage',
    name: 'Sage',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#78a896', to: '#456962', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#d4e8e3',
    accentColor: '#b0d7d0',
    pageColor: '#7bb5a8',
    brandColor: '#ffffff',
    watermarkColor: '#4a7c6f',
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#f5d5e1', to: '#fffbfe', angle: 135 },
    titleColor: '#880e4f',
    bodyColor: '#c2185b',
    accentColor: '#e91e63',
    pageColor: '#ff69b4',
    brandColor: '#880e4f',
    watermarkColor: '#f8bbd0',
  },
  {
    id: 'lavender-field',
    name: 'Lavender Field',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#c9b1e6', to: '#e8d5f5', angle: 135 },
    titleColor: '#4a235a',
    bodyColor: '#6a3d7c',
    accentColor: '#9370db',
    pageColor: '#b19cd9',
    brandColor: '#4a235a',
    watermarkColor: '#ede7f6',
  },
  // ── Luxury & Sophisticated Themes ──────────────────────────────────
  {
    id: 'marble',
    name: 'Marble',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#e8e4e0', to: '#ccc7c3', angle: 45 },
    titleColor: '#2d2622',
    bodyColor: '#5a4d47',
    accentColor: '#8b8680',
    pageColor: '#a39c95',
    brandColor: '#2d2622',
    watermarkColor: '#d4ccc5',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#f4d1c8', to: '#d4a5a0', angle: 135 },
    titleColor: '#6d4c4a',
    bodyColor: '#8b6b69',
    accentColor: '#d4a199',
    pageColor: '#d9a09f',
    brandColor: '#6d4c4a',
    watermarkColor: '#f0e5e0',
  },
  {
    id: 'midnight-gold',
    name: 'Midnight Gold',
    pro: true,
    font: "Georgia, serif",
    bg: { type: 'gradient', from: '#0f172a', to: '#1a1f3a', angle: 135 },
    titleColor: '#fef3c7',
    bodyColor: '#fde047',
    accentColor: '#fbbf24',
    pageColor: '#d97706',
    brandColor: '#fef3c7',
    watermarkColor: '#1f2937',
  },
  {
    id: 'pearl',
    name: 'Pearl',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#f8f9fa' },
    titleColor: '#1a1a1a',
    bodyColor: '#4a4a4a',
    accentColor: '#c0c0c0',
    pageColor: '#d3d3d3',
    brandColor: '#1a1a1a',
    watermarkColor: '#e8e8e8',
  },
  // ── Modern & Tech Themes ──────────────────────────────────────────
  {
    id: 'neon-night',
    name: 'Neon Night',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#0a0e27' },
    titleColor: '#00ff00',
    bodyColor: '#00ffff',
    accentColor: '#ff00ff',
    pageColor: '#ff0080',
    brandColor: '#00ff00',
    watermarkColor: '#1a0a3f',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    pro: true,
    font: "'Courier New', monospace",
    bg: { type: 'gradient', from: '#0d0221', to: '#1d0043', angle: 135 },
    titleColor: '#ff006e',
    bodyColor: '#00f5ff',
    accentColor: '#ffbe0b',
    pageColor: '#8338ec',
    brandColor: '#ff006e',
    watermarkColor: '#3a0e4d',
  },
  {
    id: 'minimal-black',
    name: 'Minimal Black',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#1a1a1a' },
    titleColor: '#ffffff',
    bodyColor: '#d4d4d4',
    accentColor: '#b0b0b0',
    pageColor: '#4a4a4a',
    brandColor: '#ffffff',
    watermarkColor: '#333333',
  },
  {
    id: 'minimal-white',
    name: 'Minimal White',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'solid', color: '#ffffff' },
    titleColor: '#000000',
    bodyColor: '#333333',
    accentColor: '#666666',
    pageColor: '#cccccc',
    brandColor: '#000000',
    watermarkColor: '#e8e8e8',
  },
  {
    id: 'teal-tech',
    name: 'Teal Tech',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#001a4d', to: '#004d66', angle: 135 },
    titleColor: '#00ffff',
    bodyColor: '#80ffff',
    accentColor: '#00d9ff',
    pageColor: '#00b3cc',
    brandColor: '#00ffff',
    watermarkColor: '#003d4d',
  },
  // ── Aesthetic & Vibe Themes ──────────────────────────────────────────
  {
    id: 'sunset-bliss',
    name: 'Sunset Bliss',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ff7e5f', to: '#fe5f45', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#ffe4d6',
    accentColor: '#fff4e6',
    pageColor: '#ffb380',
    brandColor: '#ffffff',
    watermarkColor: '#ff9966',
  },
  {
    id: 'warm-coffee',
    name: 'Warm Coffee',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#6f4e37', to: '#4a2a1a', angle: 135 },
    titleColor: '#f5deb3',
    bodyColor: '#daa520',
    accentColor: '#cd853f',
    pageColor: '#8b6914',
    brandColor: '#f5deb3',
    watermarkColor: '#5c4228',
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#1abc9c', to: '#0d9175', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#e0f7f4',
    accentColor: '#a8e6e1',
    pageColor: '#5cd6c8',
    brandColor: '#ffffff',
    watermarkColor: '#087968',
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    pro: true,
    font: "'Segoe UI', system-ui, -apple-system, Roboto, sans-serif",
    bg: { type: 'gradient', from: '#ff6b35', to: '#ff4500', angle: 135 },
    titleColor: '#ffffff',
    bodyColor: '#ffe8d6',
    accentColor: '#ffd9b3',
    pageColor: '#ffb366',
    brandColor: '#ffffff',
    watermarkColor: '#ff8c42',
  },
];

window.getTemplate = function (id) {
  return window.TEMPLATES.find((t) => t.id === id) || window.TEMPLATES[0];
};
