/* Swipely — theme definitions.
 * bg: { type:'solid', color } | { type:'gradient', from, to, angle }
 * overlay (optional): 'damask' | 'baroque' | 'art-deco' | 'cathedral' | 'manuscript'
 *   Pattern overlays are drawn on the canvas after the background fill using the
 *   theme's titleColor at low opacity — dark themes get light patterns, light get dark.
 */
window.TEMPLATES = [
  // ── Free ─────────────────────────────────────────────────────────────────────
  {
    id: 'midnight',
    name: 'Midnight',
    pro: false,
    font: "'Segoe UI', system-ui, sans-serif",
    bg: { type: 'solid', color: '#0f172a' },
    titleColor: '#ffffff', bodyColor: '#cbd5e1', accentColor: '#38bdf8',
    pageColor: '#64748b', brandColor: '#ffffff', watermarkColor: '#475569',
  },
  {
    id: 'paper',
    name: 'Paper',
    pro: false,
    font: "'Segoe UI', system-ui, sans-serif",
    bg: { type: 'solid', color: '#faf7f2' },
    titleColor: '#1a1a1a', bodyColor: '#4b4b4b', accentColor: '#e1463b',
    pageColor: '#b8b0a4', brandColor: '#1a1a1a', watermarkColor: '#c8c0b4',
  },
  {
    id: 'mono',
    name: 'Mono',
    pro: false,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'solid', color: '#000000' },
    titleColor: '#ffffff', bodyColor: '#a3a3a3', accentColor: '#ffffff',
    pageColor: '#525252', brandColor: '#ffffff', watermarkColor: '#404040',
  },
  {
    id: 'mint',
    name: 'Mint',
    pro: false,
    font: "'Segoe UI', system-ui, sans-serif",
    bg: { type: 'solid', color: '#ecfdf5' },
    titleColor: '#064e3b', bodyColor: '#047857', accentColor: '#10b981',
    pageColor: '#6ee7b7', brandColor: '#064e3b', watermarkColor: '#a7f3d0',
  },

  // ── Pro: gradients ────────────────────────────────────────────────────────────
  {
    id: 'sunset',
    name: 'Sunset',
    pro: true,
    font: "'Segoe UI', system-ui, sans-serif",
    bg: { type: 'gradient', from: '#f97316', to: '#db2777', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#ffe4e6', accentColor: '#fde68a',
    pageColor: '#fbcfe8', brandColor: '#ffffff', watermarkColor: '#fbcfe8',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    pro: true,
    font: "'Segoe UI', system-ui, sans-serif",
    bg: { type: 'gradient', from: '#0ea5e9', to: '#1e3a8a', angle: 135 },
    titleColor: '#ffffff', bodyColor: '#dbeafe', accentColor: '#67e8f9',
    pageColor: '#93c5fd', brandColor: '#ffffff', watermarkColor: '#93c5fd',
  },
  {
    id: 'midnight-gold',
    name: 'Midnight Gold',
    pro: true,
    font: "Georgia, serif",
    bg: { type: 'gradient', from: '#0f172a', to: '#1a1f3a', angle: 135 },
    titleColor: '#fef3c7', bodyColor: '#fde047', accentColor: '#fbbf24',
    pageColor: '#d97706', brandColor: '#fef3c7', watermarkColor: '#1f2937',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#f4d1c8', to: '#d4a5a0', angle: 135 },
    titleColor: '#6d4c4a', bodyColor: '#8b6b69', accentColor: '#d4a199',
    pageColor: '#d9a09f', brandColor: '#6d4c4a', watermarkColor: '#f0e5e0',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    pro: true,
    font: "'Courier New', monospace",
    bg: { type: 'gradient', from: '#0d0221', to: '#1d0043', angle: 135 },
    titleColor: '#ff006e', bodyColor: '#00f5ff', accentColor: '#ffbe0b',
    pageColor: '#8338ec', brandColor: '#ff006e', watermarkColor: '#3a0e4d',
  },
  {
    id: 'neon-night',
    name: 'Neon Night',
    pro: true,
    font: "'Segoe UI', system-ui, sans-serif",
    bg: { type: 'solid', color: '#0a0e27' },
    titleColor: '#00ff00', bodyColor: '#00ffff', accentColor: '#ff00ff',
    pageColor: '#ff0080', brandColor: '#00ff00', watermarkColor: '#1a0a3f',
  },
  {
    id: 'marble',
    name: 'Marble',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#e8e4e0', to: '#ccc7c3', angle: 45 },
    titleColor: '#2d2622', bodyColor: '#5a4d47', accentColor: '#8b8680',
    pageColor: '#a39c95', brandColor: '#2d2622', watermarkColor: '#d4ccc5',
  },
  {
    id: 'autumn',
    name: 'Autumn',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#a16207', to: '#5a3a1a', angle: 135 },
    titleColor: '#fffbeb', bodyColor: '#fef3c7', accentColor: '#fcd34d',
    pageColor: '#d97706', brandColor: '#fffbeb', watermarkColor: '#78350f',
  },

  // ── Pro: pattern designs ──────────────────────────────────────────────────────
  {
    id: 'gothic-damask',
    name: 'Gothic Damask',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'solid', color: '#0a0006' },
    titleColor: '#f5e6c8', bodyColor: '#c9a96e', accentColor: '#c9a96e',
    pageColor: '#6b3d1e', brandColor: '#f5e6c8', watermarkColor: '#3d1f0a',
    overlay: 'damask',
  },
  {
    id: 'baroque',
    name: 'Baroque',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#0c0c1a', to: '#1a0c0c', angle: 135 },
    titleColor: '#f0d080', bodyColor: '#d4aa60', accentColor: '#f0d080',
    pageColor: '#8a6020', brandColor: '#f0d080', watermarkColor: '#2a1a04',
    overlay: 'baroque',
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    pro: true,
    font: "Georgia, serif",
    bg: { type: 'solid', color: '#0a1a18' },
    titleColor: '#d4c88a', bodyColor: '#a89a60', accentColor: '#d4c88a',
    pageColor: '#4a6040', brandColor: '#d4c88a', watermarkColor: '#0f2a24',
    overlay: 'art-deco',
  },
  {
    id: 'cathedral',
    name: 'Cathedral',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'gradient', from: '#0e0020', to: '#1a0035', angle: 180 },
    titleColor: '#e8d5f5', bodyColor: '#c4a0e0', accentColor: '#9b59b6',
    pageColor: '#6b2fa0', brandColor: '#e8d5f5', watermarkColor: '#2a0050',
    overlay: 'cathedral',
  },
  {
    id: 'manuscript',
    name: 'Manuscript',
    pro: true,
    font: "Georgia, 'Times New Roman', serif",
    bg: { type: 'solid', color: '#f2e8d5' },
    titleColor: '#2c1810', bodyColor: '#4a2c1a', accentColor: '#6b3a1f',
    pageColor: '#8b5a2b', brandColor: '#2c1810', watermarkColor: '#c8a878',
    overlay: 'manuscript',
  },
];

window.getTemplate = function (id) {
  return window.TEMPLATES.find((t) => t.id === id) || window.TEMPLATES[0];
};
